import fs from 'node:fs';
import path from 'node:path';
import dotenv from 'dotenv';

export interface ConfigSaveRequest {
  harnessConfig: any;
  envVars: Record<string, string>;
}

export interface ConfigSaveResponse {
  success: boolean;
  error?: string;
}

export class ConfigManager {
  private configPath: string;
  private envPath: string;

  constructor(configPath = 'harness.config.json', envPath = '.env') {
    this.configPath = path.resolve(process.cwd(), configPath);
    this.envPath = path.resolve(process.cwd(), envPath);
  }

  async saveConfig(request: ConfigSaveRequest): Promise<ConfigSaveResponse> {
    try {
      // Save harness.config.json
      const existingConfig = this.loadExistingConfig();
      const mergedConfig = { ...existingConfig, ...request.harnessConfig };
      
      fs.writeFileSync(
        this.configPath,
        JSON.stringify(mergedConfig, null, 2),
        'utf8'
      );

      // Save .env file
      this.saveEnvFile(request.envVars);

      return { success: true };
    } catch (error) {
      console.error('ConfigManager save error:', error);
      return { 
        success: false, 
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }

  private loadExistingConfig(): any {
    try {
      if (fs.existsSync(this.configPath)) {
        const content = fs.readFileSync(this.configPath, 'utf8');
        return JSON.parse(content);
      }
    } catch (error) {
      console.warn('Could not load existing config, using empty:', error);
    }
    return {};
  }

  private saveEnvFile(envVars: Record<string, string>) {
    // Load existing env vars
    let existingEnv: Record<string, string> = {};
    
    if (fs.existsSync(this.envPath)) {
      const envContent = fs.readFileSync(this.envPath, 'utf8');
      const parsed = dotenv.parse(envContent);
      existingEnv = parsed;
    }

    // Merge with new values
    const mergedEnv = { ...existingEnv, ...envVars };

    // Write back with comments
    const envLines = [
      '# ─── M.A.I. Environment Configuration ──────────────────────────────────────',
      '# Auto-generated by M.A.I. Configuration UI',
      `# Last updated: ${new Date().toISOString()}`,
      ''
    ];

    for (const [key, value] of Object.entries(mergedEnv)) {
      if (value && value.trim()) {
        envLines.push(`${key}=${value}`);
      }
    }

    fs.writeFileSync(this.envPath, envLines.join('\n'), 'utf8');
  }

  get currentConfig(): any {
    return this.loadExistingConfig();
  }
}
