// ─── M.A.I. Event Mesh Types ────────────────────────────────────────────────
// Type definitions for the pub/sub event system that enables
// asynchronous communication across M.A.I. modules and devices.

// ─── Enums ──────────────────────────────────────────────────────────────────

export type EventPriority = "low" | "normal" | "high" | "critical";
export type EventScope = "local" | "device" | "user" | "global";

// ─── Core Event ─────────────────────────────────────────────────────────────

/**
 * A single event flowing through the mesh.
 * Events are immutable once published. The `id` is generated by the mesh.
 */
export interface MeshEvent {
  /** Unique event identifier (UUID) */
  id: string;
  /**
   * Dot-namespaced event type.
   * Built-in prefixes: device., system., notification., agent., user.
   * Example: "device.battery_low", "system.cpu_high"
   */
  type: string;
  /** Originating module, device, or service name */
  source: string;
  /** Urgency level — controls delivery ordering and retry behavior */
  priority: EventPriority;
  /**
   * Routing scope:
   *   local   — only this process
   *   device  — this device (all processes)
   *   user    — all devices for this user
   *   global  — broadcast everywhere
   */
  scope: EventScope;
  /** Target device ID (required when scope = "device") */
  targetDevice?: string;
  /** Target user ID (required when scope = "user") */
  targetUser?: string;
  /** Arbitrary payload data */
  payload: Record<string, unknown>;
  /** Unix timestamp (ms) when the event was created */
  timestamp: number;
  /**
   * Time-to-live in milliseconds. Events beyond TTL are expired on delivery.
   * `0` or `undefined` means the event is persistent (never expires from queue).
   */
  ttl?: number;
}

// ─── Subscription ────────────────────────────────────────────────────────────

/**
 * A subscription to events matching a glob pattern.
 * Subscriptions can further filter by priority, scope, and source.
 */
export interface Subscription {
  /** Unique subscription ID */
  id: string;
  /**
   * Glob pattern for matching event types.
   * Uses simple glob: "*" = one segment, "**" = any depth.
   * Examples: "device.*", "system.cpu_*", "**", "notification.*"
   */
  pattern: string;
  /** Async handler invoked for each matching event */
  handler: (event: MeshEvent) => Promise<void>;
  /** Optional filters to narrow matching events */
  filter?: {
    priority?: EventPriority[];
    scope?: EventScope[];
    source?: string[];
  };
  /** Whether the subscription is currently active */
  active: boolean;
  /** Unix timestamp (ms) when this subscription was created */
  createdAt: number;
}

// ─── Dead Letter Entry ───────────────────────────────────────────────────────

/**
 * An event that failed delivery after all retries.
 */
export interface DeadLetterEntry {
  /** The original event */
  event: MeshEvent;
  /** Subscription ID that failed */
  subscriptionId: string;
  /** Error message from the last delivery attempt */
  error: string;
  /** Number of delivery attempts before giving up */
  attempts: number;
  /** When the event was moved to the dead letter queue */
  deadAt: number;
}

// ─── Statistics ──────────────────────────────────────────────────────────────

/**
 * Runtime statistics for the event mesh.
 */
export interface EventStats {
  totalPublished: number;
  totalDelivered: number;
  totalExpired: number;
  totalDropped: number;
  totalDeadLettered: number;
  activeSubscriptions: number;
  pendingEvents: number;
  deadLetterCount: number;
  /** Publish rate (events per second, rolling 60s window) */
  publishRate: number;
  /** Delivery rate (events per second, rolling 60s window) */
  deliveryRate: number;
  /** Counters broken down by event type */
  byType: Record<string, number>;
  /** Counters broken down by source */
  bySource: Record<string, number>;
}

// ─── Built-in Event Type Constants ──────────────────────────────────────────

export const EVENT_TYPES = {
  // Device events
  DEVICE_CONNECTED: "device.connected",
  DEVICE_DISCONNECTED: "device.disconnected",
  DEVICE_BATTERY_LOW: "device.battery_low",
  DEVICE_BATTERY_CRITICAL: "device.battery_critical",
  DEVICE_LOCATION_CHANGE: "device.location_change",

  // System events
  SYSTEM_CPU_HIGH: "system.cpu_high",
  SYSTEM_MEMORY_HIGH: "system.memory_high",
  SYSTEM_NETWORK_CHANGE: "system.network_change",

  // Notification events
  NOTIFICATION_RECEIVED: "notification.received",

  // Agent events
  AGENT_ACTION_EXECUTED: "agent.action_executed",
  AGENT_ERROR: "agent.error",

  // User events
  USER_ACTIVITY: "user.activity",
} as const;

/** All known event types for validation */
export const BUILTIN_EVENT_TYPES: readonly string[] = Object.values(EVENT_TYPES);

// ─── Priority Weight (for ordering) ─────────────────────────────────────────

export const PRIORITY_WEIGHT: Record<EventPriority, number> = {
  low: 0,
  normal: 1,
  high: 2,
  critical: 3,
};
